#!/bin/bash
REPO=johannestang
IMAGE=prestodb
VERSION=$(grep PRESTO_VERSION Dockerfile | head -n 1 | awk '{print $2}' | cut -d '=' -f 2)
docker tag $IMAGE_NAME ${REPO}/${IMAGE}:${VERSION}
docker push ${REPO}/${IMAGE}:${VERSION}
