#!/bin/bash
REPO=johannestang
IMAGE=hive
VERSION=$(grep HIVE_VERSION Dockerfile | head -n 1 | awk '{print $3}')-postgresql-metastore-s3
docker tag $IMAGE_NAME ${REPO}/${IMAGE}:${VERSION}
docker push ${REPO}/${IMAGE}:${VERSION}
