#!/bin/bash
REPO=johannestang
IMAGE=hadoop-namenode
VERSION=2.0.0-$(grep hadoop-base Dockerfile |  cut -d '-' -f 3)-java8
docker tag $IMAGE_NAME ${REPO}/${IMAGE}:${VERSION}
docker push ${REPO}/${IMAGE}:${VERSION}
